#!/bin/sh

cd
git init
git remote add origin git@github.com:enzuru/home.git
git fetch
git checkout origin/master -ft

cd
git clone git@github.com:enzuru/.emacs.d.git

cd
mkdir src
cd src
git clone git@github.com:enzuru/profiles.git
git clone git@github.com:enzuru/notes.git

cd
mkdir quicklisp/local-projects
git clone "https://github.com/stumpwm/stumpwm.git" "~/quicklisp/local-projects/stumpwm"
git clone "https://github.com/stumpwm/clx-truetype.git" "~/quicklisp/local-projects/clx-truetype"
git clone "https://github.com/xach/zpb-ttf.git" "~/quicklisp/local-projects/zpb-ttf"
git clone "https://github.com/stumpwm/stumpwm-contrib.git" "~/.stumpwm.d/contrib"
