;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "elixir"
        "rust"
        "ghc"
        "mc"
        "pgcli"
        "php"
        "go@1.19.1"
        "ruby@3.2.0"
        "vlc"
        "curl"
        "automake"
        "autoconf"
        "emacs-vterm"
        "python"
        "emacs-native-comp"
        "openjdk@18:jdk"
        "exercism"
        "openjdk@18"
        "bind"
        "docker"
        "clojure"
        "gnupg@2.2.32"
        "pianobar"
        "nyxt"
        "gimp"
        "icecat"
        "node@14"
        "dbus"
        "screenfetch"
        "offlineimap3"
        "git"
        "notmuch"
        "mg"
        "xset"
        "xhost"
        "xsetroot"
        "xterm"
        "xrdb"
        "xfontsel"
        "irssi"
        "fontconfig"
        "font-iosevka"
        "links"
        "ntp"
        "sbcl"
        "glances"
        "rxvt-unicode"
        "guile@3.0.8"
        "aspell-dict-en"
        "hunspell-dict-en-us"
        "hunspell"
        "ispell"
        "aspell"
        "htop"
        "leiningen"
        "gcc-toolchain@12.2"
        "libvterm"
        "setxkbmap"
        "unzip"
        "gpm"
        "make"
        "neofetch"
        "the-silver-searcher"))
